name: Publish Website

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: |
          npm i
      - name: Build Website
        run: |
          npm run build
          echo "meetup.microfrontends.cloud" > dist/CNAME
          echo "# Disable Jekyll" > dist/.nojekyll
      - name: Deploy Website
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d "dist" -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
